tasks/urls.py
from django.urls import path
from tasks import views


app_name = "tasks"

urlpatterns = [
    path("", views.tasks_manager, name="tasks_manager"),
    path("delete/<int:pk>/", views.delete_task, name="delete")
]

to_do_web_app/urls.py
from django.contrib import admin
from django.urls import path, include
from tasks import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name="index"),
    path("tasks/", include("tasks.urls"))
]

tasks/models.py
from django.db import models


class Task(models.Model):
    task_name = models.CharField(max_length=150)

    def __str__(self):
        return self.task_name

tasks/forms.py
from django import forms
from .models import Task


class FormTask(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"

tasks/views.py
from django.shortcuts import render, redirect
from .models import Task
from .forms import FormTask


def index(request):
    all_tasks = Task.objects.all()
    context = {"all_tasks": all_tasks}
    return render(request, "tasks/index.html", context)


def tasks_manager(request):
    form = FormTask
    all_tasks = Task.objects.all()
    context = {
        "form": form,
        "all_tasks": all_tasks,
    }

    if request.method == "POST":
        form = FormTask(request.POST)
        if form.is_valid():
            form.save()

            # to clear the form after submitting a task:
            form = FormTask()

            # return redirect("tasks:tasks_manager")
    return render(request, "tasks/task_manager.html", context)


def delete_task(request, pk):
    item = Task.objects.get(id=pk)
    item.delete()

    return redirect("tasks:tasks_manager")

tasks/templates/tasks/index.html
{% extends "base.html" %}

{% block title %}To Do Web App{% endblock %}

{% block content %}
    <div class="container" align="center">
        <div class="jumbotron">
            <h1>Welcome to your To-Do Page</h1>

        </div>
    </div>

<!--    Shows all created tasks and have a button to open the manager page
where you can create and delete the tasks-->

    <div class="container">
        <div class="jumbotron">
            <a href="{% url 'tasks:tasks_manager' %}"><button type="button" class="btn btn-info">Manage your tasks</button></a>
            <!--            create space between the elements-->
            <p></p>

            {% if all_tasks %}
                <ol class="list-group">
                    {% for task in all_tasks %}
                        <li class="list-group-item">{{ task.task_name }}</li>
                    {% endfor %}
                </ol>
            {% else %}
                <h4>You have no tasks</h4>
            {% endif %}
        </div>

    </div>

{% endblock %}

tasks/templates/tasks/task_manager.html
{% extends "base.html" %}

{% block title %}Tasks Manager{% endblock %}

{% block content %}

<!--    Add new task form-->
    <div class="container">
        <div class="jumbotron">
            <h3>Create New Task:</h3>
            <form class="form-inline" method="POST">
                <div class="form-group-item">
                    {% csrf_token %}
                    {{ form.task_name }}
                    <button class="btn btn-info" type="submit">Add</button>
                </div>
            </form>
        </div>
    </div>

<!--    Show all of the created tasks as well as button "delete" for each one of them-->
     <div class="container">
        <div class="jumbotron">
            <h3>Your Current Tasks:</h3>
            {% if all_tasks %}
                <ol class="list-group">
                    {% for task in all_tasks %}
                        <li class="list-group-item">
                                {{ task.task_name }}
                                <a href="{% url 'tasks:delete' task.id %}">
                                    <button class="btn btn-info" type="button">Delete</button>
                                </a>
                        </li>
                    {% endfor %}
                </ol>
            {% else %}
                <h4>You have no tasks</h4>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</head>
<body>

<!--    Navbar-->
    <div class="container">
        <nav class="navbar navbar-dark bg-dark navbar-static-top">
            <button type="button" class="btn btn-info"><a class="navbar-brand" href="{% url 'index' %}">To Do App</a></button>
         </nav>
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>